### ISSUE TITLE
Question about learning it in distributed scheme

### ISSUE THREAD

**Issue by e0jun** [kaist-dmlab/DF-TAR#1]
Thanks for your great work:)

I wanna run it in multiple GPUs using tf.distribute.
Could you update it for that?

**Comment by itouchz** [comment]
Thank you for the suggestion. You can easily add strategy.scope() following steps in https://www.tensorflow.org/tutorials/distribute/keras#create_the_model to compile our model, as shown in the Example Run.ipynb file before executing the model.fit() to run the model in distributed mode.
